apiVersion: v1 
kind: Service
metadata: 
  name: myfirstproject-svc
  labels:
    app: myfirstprojectapp
    version: 2.6.1
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32000
    protocol: TCP
  selector:
    app: myfirstprojectapp
    version: 2.6.1