apiVersion: v1 
kind: service
metadata:
  name: vertex-svc
  labels:
    app: myvertexapp
    version: 2.6.1
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: myvertexapp
    version: 2.6.1