apiVersion: v1
kind: ReplicationController
metadata:
  name: myfirstproject-rcc
spec:
  replicas: 3
  selector:
    app: myfirstprojectapp1
    version: 2.6.1
  template:
    metadata:
      labels:
        app: myfirstprojectapp1
        version: 2.6.1
    spec:
      containers:
      - name: myhealetapp-container
        image: ambika366/htmlfirstproject22july:1
        ports:
        - containerPort: 80
      
--- 

apiVersion: v1
kind: ReplicationController
metadata:
  name: myfirstproject-rcc
spec:
  replicas: 3
  selector:
    app: myfirstprojectapp2
    version: 2.6.2
  template:
    metadata:
      labels:
        app: myfirstprojectapp2
        version: 2.6.2
    spec:
      containers:
      - name: myhealetapp-container
        image: ambika366/htmlfirstproject22july:1
        ports:
        - containerPort: 80