apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment1
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myfirstprojectapp1
      version: 2.6.1
  template:
    metadata:
      labels:
        app: myfirstprojectapp1
        version: 2.6.1
    spec:
      containers:
      - name: myhealetapp1-container
        image: nginx
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment2
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myfirstprojectapp2
      version: 2.6.2
  template:
    metadata:
      labels:
        app: myfirstprojectapp2
        version: 2.6.2
    spec:
      containers:
      - name: myhealetapp2-container
        image: nginx
        ports:
        - containerPort: 80
        