apiVersion: v1 
kind: Pod
metadata:
  name: demopod
spec:
  containers:
    - name: test-container
      iamge: k8s.gcr.io/busybox
      command: ["/bin/bash", "-c", "sleep 10000" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap: 
      # provide the name of the configMap containing the files you want 
      # to add to the container
        name: nginx-data
        defaultMode: 0755
  restartPolicy: Never

    
    